import Head from "next/head";
import React from "react";
import Footer2 from "../footer/Footer2";
import Header from "../header/Header";

function Layout({ children }) {
  return (
    <>
      <Head>
        <title>뉴저지 한인 변호사 검색 | Lawyer Banc</title>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge"></meta>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="assets/images/faviconS.png"
          type="image/gif"
          sizes="20x20"
        />
      </Head>
      <Header />
      {children}
      <Footer2 />
    </>
  );
}

export default Layout;
