import Head from "next/head";
import React from "react";
import Banner3 from "../components/banner/Banner3";
import Home3Blog3 from "../components/blog/Home3Blog3";
import Footer3 from "../components/footer/Footer3";
import Header1 from "../components/header/Header1";
import HowItWrok3 from "../components/howItWork/HowItWrok3";
import BestService from "../components/service/BestService";
import CreativeService3 from "../components/service/CreativeService3";
import PopularService3 from "../components/service/PopularService3";
import RegularSerice3 from "../components/service/RegularSerice3";
import Shop3 from "../components/shop/Shop3";
import Testimonial3 from "../components/testimonial/Testimonial3";
import WhyChooseUs3 from "../components/whyChooseUs/WhyChooseUs3";

function HomePageThree() {
  return (
    <>
      <Head>
        <title>SERVE - On Demand Services Next JS Template</title>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge"></meta>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="assets/images/faviconS.png"
          type="image/gif"
          sizes="20x20"
        />
      </Head>
      <Header1 />
      <Banner3 />
      <CreativeService3 />
      <BestService />
      <PopularService3 />
      <WhyChooseUs3 />
      <RegularSerice3 />
      <Shop3 />
      <Testimonial3 />
      <HowItWrok3 />
      <Home3Blog3 />
      <Footer3 />
    </>
  );
}

export default HomePageThree;
