import Head from "next/head";
import React from "react";
import Banner2 from "../components/banner/Banner2";
import Home2Blog from "../components/blog/Home2Blog";
import Header1 from "../components/header/Header1";
import WorkProcess2 from "../components/howItWork/WorkProcess2";
import CreativeService2 from "../components/service/CreativeService2";
import OfferService2 from "../components/service/OfferService2";
import PopularService2 from "../components/service/PopularService2";
import FeatureShop2 from "../components/shop/FeatureShop2";
import Testimonial2 from "../components/testimonial/Testimonial2";
import WhyChooseus2 from "../components/whyChooseUs/WhyChooseus2";
import Footer2 from "./../components/footer/Footer2";
function HomePagetwo() {
  return (
    <>
      <Head>
        <title>SERVE - On Demand Services Next JS Template</title>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge"></meta>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="assets/images/faviconS.png"
          type="image/gif"
          sizes="20x20"
        />
      </Head>
      <Header1 />
      <Banner2 />
      <CreativeService2 />
      <FeatureShop2 />
      <PopularService2 />
      <OfferService2 />
      <WorkProcess2 />
      <Testimonial2 />
      <WhyChooseus2 />
      <Home2Blog />
      <Footer2 />
    </>
  );
}

export default HomePagetwo;
